### ISSUE TITLE
Permission Error in "tools" directory as "vnc" user

### ISSUE THREAD

**Issue by KyleEvers** [cisagov/ansible-role-kali#5] opened 2020-03-20 12:31 UTC
# 🐛 Bug Report

The `tools` directory and projects installed into the directory are installed by `root` but the default user is `vnc`. This results in permission errors when trying to run tools or writing files in `/tools` as the `vnc` user. 

## To Reproduce

```bash
cd /tools/SimplyEmail
./SimplyEmail.py -h
```

or 

```bash
cd /tools; echo test > test.txt

```

## Expected behavior

The tool to run/file be written.

## Any helpful log output

Example of permission error:

```bash
Traceback (most recent call last):
  File "./SimplyEmail.py", line 113, in <module>
    main()
  File "./SimplyEmail.py", line 108, in main
    TaskStarter(version)
  File "./SimplyEmail.py", line 60, in TaskStarter
    log.start()
  File "/tools/SimplyEmail/Helpers/helpers.py", line 157, in start
    fh = logging.FileHandler(self.name)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tools/SimplyEmail/.SimplyEmail.log'

```
and 
```bash
bash: test.txt: Permission denied
```

**Comment by jsf9k** [comment] 2020-03-23 21:44
Fixed via #7 and cisagov/kali-packer#11.

**Comment by jsf9k** [comment] 2020-03-27 14:34
I'm still tying up some loose ends to allow me to access the Kali instances in our env0-staging environment.  Once that is complete I will be able to verify that the issue is fixed.

After that, we will deploy these changes to env0-production so that @KyleEvers can verify and close this issue.

**Comment by jsf9k** [comment] 2020-03-30 20:19
Confirmed that `/tools` is now accessible by `vnc` in env0-staging.

**Comment by dav3r** [comment] 2020-04-03 14:05
@KyleEvers - Can you please verify that this issue has been resolved in `env0-production`?

**Comment by felddy** [comment] 2020-04-24 18:10
@KyleEvers We need a verification please so we can close this.

**Comment by KyleEvers** [comment] 2020-04-27 19:33
LGTM 👍

**Comment by jsf9k** [comment] 2020-04-27 19:33
Verified at last!

**Closed as completed by jsf9k** 2020-04-27 19:33 UTC
Labels: bug
